/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RandevuRouteImport } from './routes/randevu'
import { Route as OgImageDotjpgRouteImport } from './routes/og-image[.]jpg'
import { Route as KvkkRouteImport } from './routes/kvkk'
import { Route as IndexDurumuBanglaRouteImport } from './routes/index-durumu-bangla'
import { Route as HizmetlerRouteImport } from './routes/hizmetler'
import { Route as HisabRouteImport } from './routes/hisab'
import { Route as GoogleAdsKurulumRouteImport } from './routes/google-ads-kurulum'
import { Route as GoogleAdsRouteImport } from './routes/google-ads'
import { Route as DisavowRouteImport } from './routes/disavow'
import { Route as CerezPolitikasiRouteImport } from './routes/cerez-politikasi'
import { Route as BlogYazmaRehberiRouteImport } from './routes/blog-yazma-rehberi'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AcilTesisatciRouteImport } from './routes/acil-tesisatci'
import { Route as SEOOverviewBanglaRouteImport } from './routes/SEO-overview-bangla'
import { Route as SEOOverviewRouteImport } from './routes/SEO-overview'
import { Route as DesktopViewRouteImport } from './routes/Desktop-view'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TesisatciIndexRouteImport } from './routes/tesisatci.index'
import { Route as HisabIndexRouteImport } from './routes/hisab.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TesisatciSlugRouteImport } from './routes/tesisatci.$slug'
import { Route as StudioLoginRouteImport } from './routes/studio.login'
import { Route as HizmetSlugRouteImport } from './routes/hizmet.$slug'
import { Route as HisabWarehousesRouteImport } from './routes/hisab.warehouses'
import { Route as HisabWarehouseStockRouteImport } from './routes/hisab.warehouse-stock'
import { Route as HisabSuppliersRouteImport } from './routes/hisab.suppliers'
import { Route as HisabStockRouteImport } from './routes/hisab.stock'
import { Route as HisabSettingsRouteImport } from './routes/hisab.settings'
import { Route as HisabSearchRouteImport } from './routes/hisab.search'
import { Route as HisabReportsRouteImport } from './routes/hisab.reports'
import { Route as HisabProductsRouteImport } from './routes/hisab.products'
import { Route as HisabPartiesRouteImport } from './routes/hisab.parties'
import { Route as HisabNewRouteImport } from './routes/hisab.new'
import { Route as HisabMoreRouteImport } from './routes/hisab.more'
import { Route as HisabLoginRouteImport } from './routes/hisab.login'
import { Route as HisabListRouteImport } from './routes/hisab.list'
import { Route as HisabHelpRouteImport } from './routes/hisab.help'
import { Route as HisabFilesRouteImport } from './routes/hisab.files'
import { Route as HisabCustomersRouteImport } from './routes/hisab.customers'
import { Route as HisabCapitalRouteImport } from './routes/hisab.capital'
import { Route as HisabActivityRouteImport } from './routes/hisab.activity'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminSeoWriterRouteImport } from './routes/admin.seo-writer'
import { Route as AdminSeoDataRouteImport } from './routes/admin.seo-data'
import { Route as AdminSearchConsoleRouteImport } from './routes/admin.search-console'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminPipelineRouteImport } from './routes/admin.pipeline'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminKeywordsRouteImport } from './routes/admin.keywords'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminContactClicksRouteImport } from './routes/admin.contact-clicks'
import { Route as AdminCallbacksRouteImport } from './routes/admin.callbacks'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as TesisatciSlugIndexRouteImport } from './routes/tesisatci.$slug.index'
import { Route as HizmetSlugIndexRouteImport } from './routes/hizmet.$slug.index'
import { Route as TesisatciSlugServiceRouteImport } from './routes/tesisatci.$slug.$service'
import { Route as HizmetSlugFiyatRouteImport } from './routes/hizmet.$slug.fiyat'
import { Route as HisabSupplierIdRouteImport } from './routes/hisab.supplier.$id'
import { Route as HisabInvoiceIdRouteImport } from './routes/hisab.invoice.$id'
import { Route as HisabCustomerIdRouteImport } from './routes/hisab.customer.$id'
import { Route as ApiHisabScanRouteImport } from './routes/api/hisab/scan'
import { Route as TesisatciSlugMahalleNeighborhoodRouteImport } from './routes/tesisatci.$slug.mahalle.$neighborhood'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicRCodeRouteImport } from './routes/api/public/r/$code'
import { Route as ApiPublicHooksRefreshAnalyticsRouteImport } from './routes/api/public/hooks/refresh-analytics'
import { Route as ApiPublicHooksPublishSocialRouteImport } from './routes/api/public/hooks/publish-social'
import { Route as ApiPublicHooksMetaWebhookRouteImport } from './routes/api/public/hooks/meta-webhook'
import { Route as ApiPublicHooksKeywordSnapshotRouteImport } from './routes/api/public/hooks/keyword-snapshot'
import { Route as ApiPublicHooksContactAlertRouteImport } from './routes/api/public/hooks/contact-alert'
import { Route as ApiPublicHooksAutopilotRouteImport } from './routes/api/public/hooks/autopilot'
import { Route as ApiPublicHooksAutomationRouteImport } from './routes/api/public/hooks/automation'

const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RandevuRoute = RandevuRouteImport.update({
  id: '/randevu',
  path: '/randevu',
  getParentRoute: () => rootRouteImport,
} as any)
const OgImageDotjpgRoute = OgImageDotjpgRouteImport.update({
  id: '/og-image.jpg',
  path: '/og-image.jpg',
  getParentRoute: () => rootRouteImport,
} as any)
const KvkkRoute = KvkkRouteImport.update({
  id: '/kvkk',
  path: '/kvkk',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexDurumuBanglaRoute = IndexDurumuBanglaRouteImport.update({
  id: '/index-durumu-bangla',
  path: '/index-durumu-bangla',
  getParentRoute: () => rootRouteImport,
} as any)
const HizmetlerRoute = HizmetlerRouteImport.update({
  id: '/hizmetler',
  path: '/hizmetler',
  getParentRoute: () => rootRouteImport,
} as any)
const HisabRoute = HisabRouteImport.update({
  id: '/hisab',
  path: '/hisab',
  getParentRoute: () => rootRouteImport,
} as any)
const GoogleAdsKurulumRoute = GoogleAdsKurulumRouteImport.update({
  id: '/google-ads-kurulum',
  path: '/google-ads-kurulum',
  getParentRoute: () => rootRouteImport,
} as any)
const GoogleAdsRoute = GoogleAdsRouteImport.update({
  id: '/google-ads',
  path: '/google-ads',
  getParentRoute: () => rootRouteImport,
} as any)
const DisavowRoute = DisavowRouteImport.update({
  id: '/disavow',
  path: '/disavow',
  getParentRoute: () => rootRouteImport,
} as any)
const CerezPolitikasiRoute = CerezPolitikasiRouteImport.update({
  id: '/cerez-politikasi',
  path: '/cerez-politikasi',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogYazmaRehberiRoute = BlogYazmaRehberiRouteImport.update({
  id: '/blog-yazma-rehberi',
  path: '/blog-yazma-rehberi',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AcilTesisatciRoute = AcilTesisatciRouteImport.update({
  id: '/acil-tesisatci',
  path: '/acil-tesisatci',
  getParentRoute: () => rootRouteImport,
} as any)
const SEOOverviewBanglaRoute = SEOOverviewBanglaRouteImport.update({
  id: '/SEO-overview-bangla',
  path: '/SEO-overview-bangla',
  getParentRoute: () => rootRouteImport,
} as any)
const SEOOverviewRoute = SEOOverviewRouteImport.update({
  id: '/SEO-overview',
  path: '/SEO-overview',
  getParentRoute: () => rootRouteImport,
} as any)
const DesktopViewRoute = DesktopViewRouteImport.update({
  id: '/Desktop-view',
  path: '/Desktop-view',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TesisatciIndexRoute = TesisatciIndexRouteImport.update({
  id: '/tesisatci/',
  path: '/tesisatci/',
  getParentRoute: () => rootRouteImport,
} as any)
const HisabIndexRoute = HisabIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HisabRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TesisatciSlugRoute = TesisatciSlugRouteImport.update({
  id: '/tesisatci/$slug',
  path: '/tesisatci/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioLoginRoute = StudioLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => StudioRoute,
} as any)
const HizmetSlugRoute = HizmetSlugRouteImport.update({
  id: '/hizmet/$slug',
  path: '/hizmet/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HisabWarehousesRoute = HisabWarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => HisabRoute,
} as any)
const HisabWarehouseStockRoute = HisabWarehouseStockRouteImport.update({
  id: '/warehouse-stock',
  path: '/warehouse-stock',
  getParentRoute: () => HisabRoute,
} as any)
const HisabSuppliersRoute = HisabSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => HisabRoute,
} as any)
const HisabStockRoute = HisabStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => HisabRoute,
} as any)
const HisabSettingsRoute = HisabSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => HisabRoute,
} as any)
const HisabSearchRoute = HisabSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => HisabRoute,
} as any)
const HisabReportsRoute = HisabReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => HisabRoute,
} as any)
const HisabProductsRoute = HisabProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => HisabRoute,
} as any)
const HisabPartiesRoute = HisabPartiesRouteImport.update({
  id: '/parties',
  path: '/parties',
  getParentRoute: () => HisabRoute,
} as any)
const HisabNewRoute = HisabNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => HisabRoute,
} as any)
const HisabMoreRoute = HisabMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => HisabRoute,
} as any)
const HisabLoginRoute = HisabLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => HisabRoute,
} as any)
const HisabListRoute = HisabListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => HisabRoute,
} as any)
const HisabHelpRoute = HisabHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => HisabRoute,
} as any)
const HisabFilesRoute = HisabFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => HisabRoute,
} as any)
const HisabCustomersRoute = HisabCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => HisabRoute,
} as any)
const HisabCapitalRoute = HisabCapitalRouteImport.update({
  id: '/capital',
  path: '/capital',
  getParentRoute: () => HisabRoute,
} as any)
const HisabActivityRoute = HisabActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => HisabRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSeoWriterRoute = AdminSeoWriterRouteImport.update({
  id: '/seo-writer',
  path: '/seo-writer',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeoDataRoute = AdminSeoDataRouteImport.update({
  id: '/seo-data',
  path: '/seo-data',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSearchConsoleRoute = AdminSearchConsoleRouteImport.update({
  id: '/search-console',
  path: '/search-console',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPipelineRoute = AdminPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKeywordsRoute = AdminKeywordsRouteImport.update({
  id: '/keywords',
  path: '/keywords',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactClicksRoute = AdminContactClicksRouteImport.update({
  id: '/contact-clicks',
  path: '/contact-clicks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCallbacksRoute = AdminCallbacksRouteImport.update({
  id: '/callbacks',
  path: '/callbacks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const TesisatciSlugIndexRoute = TesisatciSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TesisatciSlugRoute,
} as any)
const HizmetSlugIndexRoute = HizmetSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HizmetSlugRoute,
} as any)
const TesisatciSlugServiceRoute = TesisatciSlugServiceRouteImport.update({
  id: '/$service',
  path: '/$service',
  getParentRoute: () => TesisatciSlugRoute,
} as any)
const HizmetSlugFiyatRoute = HizmetSlugFiyatRouteImport.update({
  id: '/fiyat',
  path: '/fiyat',
  getParentRoute: () => HizmetSlugRoute,
} as any)
const HisabSupplierIdRoute = HisabSupplierIdRouteImport.update({
  id: '/supplier/$id',
  path: '/supplier/$id',
  getParentRoute: () => HisabRoute,
} as any)
const HisabInvoiceIdRoute = HisabInvoiceIdRouteImport.update({
  id: '/invoice/$id',
  path: '/invoice/$id',
  getParentRoute: () => HisabRoute,
} as any)
const HisabCustomerIdRoute = HisabCustomerIdRouteImport.update({
  id: '/customer/$id',
  path: '/customer/$id',
  getParentRoute: () => HisabRoute,
} as any)
const ApiHisabScanRoute = ApiHisabScanRouteImport.update({
  id: '/api/hisab/scan',
  path: '/api/hisab/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const TesisatciSlugMahalleNeighborhoodRoute =
  TesisatciSlugMahalleNeighborhoodRouteImport.update({
    id: '/mahalle/$neighborhood',
    path: '/mahalle/$neighborhood',
    getParentRoute: () => TesisatciSlugRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRCodeRoute = ApiPublicRCodeRouteImport.update({
  id: '/api/public/r/$code',
  path: '/api/public/r/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksRefreshAnalyticsRoute =
  ApiPublicHooksRefreshAnalyticsRouteImport.update({
    id: '/api/public/hooks/refresh-analytics',
    path: '/api/public/hooks/refresh-analytics',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPublishSocialRoute =
  ApiPublicHooksPublishSocialRouteImport.update({
    id: '/api/public/hooks/publish-social',
    path: '/api/public/hooks/publish-social',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMetaWebhookRoute =
  ApiPublicHooksMetaWebhookRouteImport.update({
    id: '/api/public/hooks/meta-webhook',
    path: '/api/public/hooks/meta-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksKeywordSnapshotRoute =
  ApiPublicHooksKeywordSnapshotRouteImport.update({
    id: '/api/public/hooks/keyword-snapshot',
    path: '/api/public/hooks/keyword-snapshot',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksContactAlertRoute =
  ApiPublicHooksContactAlertRouteImport.update({
    id: '/api/public/hooks/contact-alert',
    path: '/api/public/hooks/contact-alert',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAutopilotRoute = ApiPublicHooksAutopilotRouteImport.update({
  id: '/api/public/hooks/autopilot',
  path: '/api/public/hooks/autopilot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksAutomationRoute =
  ApiPublicHooksAutomationRouteImport.update({
    id: '/api/public/hooks/automation',
    path: '/api/public/hooks/automation',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Desktop-view': typeof DesktopViewRoute
  '/SEO-overview': typeof SEOOverviewRoute
  '/SEO-overview-bangla': typeof SEOOverviewBanglaRoute
  '/acil-tesisatci': typeof AcilTesisatciRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog-yazma-rehberi': typeof BlogYazmaRehberiRoute
  '/cerez-politikasi': typeof CerezPolitikasiRoute
  '/disavow': typeof DisavowRoute
  '/google-ads': typeof GoogleAdsRoute
  '/google-ads-kurulum': typeof GoogleAdsKurulumRoute
  '/hisab': typeof HisabRouteWithChildren
  '/hizmetler': typeof HizmetlerRoute
  '/index-durumu-bangla': typeof IndexDurumuBanglaRoute
  '/kvkk': typeof KvkkRoute
  '/og-image.jpg': typeof OgImageDotjpgRoute
  '/randevu': typeof RandevuRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRouteWithChildren
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/callbacks': typeof AdminCallbacksRoute
  '/admin/contact-clicks': typeof AdminContactClicksRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/keywords': typeof AdminKeywordsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pipeline': typeof AdminPipelineRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/search-console': typeof AdminSearchConsoleRoute
  '/admin/seo-data': typeof AdminSeoDataRoute
  '/admin/seo-writer': typeof AdminSeoWriterRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/hisab/activity': typeof HisabActivityRoute
  '/hisab/capital': typeof HisabCapitalRoute
  '/hisab/customers': typeof HisabCustomersRoute
  '/hisab/files': typeof HisabFilesRoute
  '/hisab/help': typeof HisabHelpRoute
  '/hisab/list': typeof HisabListRoute
  '/hisab/login': typeof HisabLoginRoute
  '/hisab/more': typeof HisabMoreRoute
  '/hisab/new': typeof HisabNewRoute
  '/hisab/parties': typeof HisabPartiesRoute
  '/hisab/products': typeof HisabProductsRoute
  '/hisab/reports': typeof HisabReportsRoute
  '/hisab/search': typeof HisabSearchRoute
  '/hisab/settings': typeof HisabSettingsRoute
  '/hisab/stock': typeof HisabStockRoute
  '/hisab/suppliers': typeof HisabSuppliersRoute
  '/hisab/warehouse-stock': typeof HisabWarehouseStockRoute
  '/hisab/warehouses': typeof HisabWarehousesRoute
  '/hizmet/$slug': typeof HizmetSlugRouteWithChildren
  '/studio/login': typeof StudioLoginRoute
  '/tesisatci/$slug': typeof TesisatciSlugRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/hisab/': typeof HisabIndexRoute
  '/tesisatci/': typeof TesisatciIndexRoute
  '/api/hisab/scan': typeof ApiHisabScanRoute
  '/hisab/customer/$id': typeof HisabCustomerIdRoute
  '/hisab/invoice/$id': typeof HisabInvoiceIdRoute
  '/hisab/supplier/$id': typeof HisabSupplierIdRoute
  '/hizmet/$slug/fiyat': typeof HizmetSlugFiyatRoute
  '/tesisatci/$slug/$service': typeof TesisatciSlugServiceRoute
  '/hizmet/$slug/': typeof HizmetSlugIndexRoute
  '/tesisatci/$slug/': typeof TesisatciSlugIndexRoute
  '/api/public/hooks/automation': typeof ApiPublicHooksAutomationRoute
  '/api/public/hooks/autopilot': typeof ApiPublicHooksAutopilotRoute
  '/api/public/hooks/contact-alert': typeof ApiPublicHooksContactAlertRoute
  '/api/public/hooks/keyword-snapshot': typeof ApiPublicHooksKeywordSnapshotRoute
  '/api/public/hooks/meta-webhook': typeof ApiPublicHooksMetaWebhookRoute
  '/api/public/hooks/publish-social': typeof ApiPublicHooksPublishSocialRoute
  '/api/public/hooks/refresh-analytics': typeof ApiPublicHooksRefreshAnalyticsRoute
  '/api/public/r/$code': typeof ApiPublicRCodeRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/tesisatci/$slug/mahalle/$neighborhood': typeof TesisatciSlugMahalleNeighborhoodRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Desktop-view': typeof DesktopViewRoute
  '/SEO-overview': typeof SEOOverviewRoute
  '/SEO-overview-bangla': typeof SEOOverviewBanglaRoute
  '/acil-tesisatci': typeof AcilTesisatciRoute
  '/blog-yazma-rehberi': typeof BlogYazmaRehberiRoute
  '/cerez-politikasi': typeof CerezPolitikasiRoute
  '/disavow': typeof DisavowRoute
  '/google-ads': typeof GoogleAdsRoute
  '/google-ads-kurulum': typeof GoogleAdsKurulumRoute
  '/hizmetler': typeof HizmetlerRoute
  '/index-durumu-bangla': typeof IndexDurumuBanglaRoute
  '/kvkk': typeof KvkkRoute
  '/og-image.jpg': typeof OgImageDotjpgRoute
  '/randevu': typeof RandevuRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRouteWithChildren
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/callbacks': typeof AdminCallbacksRoute
  '/admin/contact-clicks': typeof AdminContactClicksRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/keywords': typeof AdminKeywordsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pipeline': typeof AdminPipelineRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/search-console': typeof AdminSearchConsoleRoute
  '/admin/seo-data': typeof AdminSeoDataRoute
  '/admin/seo-writer': typeof AdminSeoWriterRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/hisab/activity': typeof HisabActivityRoute
  '/hisab/capital': typeof HisabCapitalRoute
  '/hisab/customers': typeof HisabCustomersRoute
  '/hisab/files': typeof HisabFilesRoute
  '/hisab/help': typeof HisabHelpRoute
  '/hisab/list': typeof HisabListRoute
  '/hisab/login': typeof HisabLoginRoute
  '/hisab/more': typeof HisabMoreRoute
  '/hisab/new': typeof HisabNewRoute
  '/hisab/parties': typeof HisabPartiesRoute
  '/hisab/products': typeof HisabProductsRoute
  '/hisab/reports': typeof HisabReportsRoute
  '/hisab/search': typeof HisabSearchRoute
  '/hisab/settings': typeof HisabSettingsRoute
  '/hisab/stock': typeof HisabStockRoute
  '/hisab/suppliers': typeof HisabSuppliersRoute
  '/hisab/warehouse-stock': typeof HisabWarehouseStockRoute
  '/hisab/warehouses': typeof HisabWarehousesRoute
  '/studio/login': typeof StudioLoginRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/hisab': typeof HisabIndexRoute
  '/tesisatci': typeof TesisatciIndexRoute
  '/api/hisab/scan': typeof ApiHisabScanRoute
  '/hisab/customer/$id': typeof HisabCustomerIdRoute
  '/hisab/invoice/$id': typeof HisabInvoiceIdRoute
  '/hisab/supplier/$id': typeof HisabSupplierIdRoute
  '/hizmet/$slug/fiyat': typeof HizmetSlugFiyatRoute
  '/tesisatci/$slug/$service': typeof TesisatciSlugServiceRoute
  '/hizmet/$slug': typeof HizmetSlugIndexRoute
  '/tesisatci/$slug': typeof TesisatciSlugIndexRoute
  '/api/public/hooks/automation': typeof ApiPublicHooksAutomationRoute
  '/api/public/hooks/autopilot': typeof ApiPublicHooksAutopilotRoute
  '/api/public/hooks/contact-alert': typeof ApiPublicHooksContactAlertRoute
  '/api/public/hooks/keyword-snapshot': typeof ApiPublicHooksKeywordSnapshotRoute
  '/api/public/hooks/meta-webhook': typeof ApiPublicHooksMetaWebhookRoute
  '/api/public/hooks/publish-social': typeof ApiPublicHooksPublishSocialRoute
  '/api/public/hooks/refresh-analytics': typeof ApiPublicHooksRefreshAnalyticsRoute
  '/api/public/r/$code': typeof ApiPublicRCodeRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/tesisatci/$slug/mahalle/$neighborhood': typeof TesisatciSlugMahalleNeighborhoodRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Desktop-view': typeof DesktopViewRoute
  '/SEO-overview': typeof SEOOverviewRoute
  '/SEO-overview-bangla': typeof SEOOverviewBanglaRoute
  '/acil-tesisatci': typeof AcilTesisatciRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog-yazma-rehberi': typeof BlogYazmaRehberiRoute
  '/cerez-politikasi': typeof CerezPolitikasiRoute
  '/disavow': typeof DisavowRoute
  '/google-ads': typeof GoogleAdsRoute
  '/google-ads-kurulum': typeof GoogleAdsKurulumRoute
  '/hisab': typeof HisabRouteWithChildren
  '/hizmetler': typeof HizmetlerRoute
  '/index-durumu-bangla': typeof IndexDurumuBanglaRoute
  '/kvkk': typeof KvkkRoute
  '/og-image.jpg': typeof OgImageDotjpgRoute
  '/randevu': typeof RandevuRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRouteWithChildren
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/callbacks': typeof AdminCallbacksRoute
  '/admin/contact-clicks': typeof AdminContactClicksRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/keywords': typeof AdminKeywordsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pipeline': typeof AdminPipelineRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/search-console': typeof AdminSearchConsoleRoute
  '/admin/seo-data': typeof AdminSeoDataRoute
  '/admin/seo-writer': typeof AdminSeoWriterRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/hisab/activity': typeof HisabActivityRoute
  '/hisab/capital': typeof HisabCapitalRoute
  '/hisab/customers': typeof HisabCustomersRoute
  '/hisab/files': typeof HisabFilesRoute
  '/hisab/help': typeof HisabHelpRoute
  '/hisab/list': typeof HisabListRoute
  '/hisab/login': typeof HisabLoginRoute
  '/hisab/more': typeof HisabMoreRoute
  '/hisab/new': typeof HisabNewRoute
  '/hisab/parties': typeof HisabPartiesRoute
  '/hisab/products': typeof HisabProductsRoute
  '/hisab/reports': typeof HisabReportsRoute
  '/hisab/search': typeof HisabSearchRoute
  '/hisab/settings': typeof HisabSettingsRoute
  '/hisab/stock': typeof HisabStockRoute
  '/hisab/suppliers': typeof HisabSuppliersRoute
  '/hisab/warehouse-stock': typeof HisabWarehouseStockRoute
  '/hisab/warehouses': typeof HisabWarehousesRoute
  '/hizmet/$slug': typeof HizmetSlugRouteWithChildren
  '/studio/login': typeof StudioLoginRoute
  '/tesisatci/$slug': typeof TesisatciSlugRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/hisab/': typeof HisabIndexRoute
  '/tesisatci/': typeof TesisatciIndexRoute
  '/api/hisab/scan': typeof ApiHisabScanRoute
  '/hisab/customer/$id': typeof HisabCustomerIdRoute
  '/hisab/invoice/$id': typeof HisabInvoiceIdRoute
  '/hisab/supplier/$id': typeof HisabSupplierIdRoute
  '/hizmet/$slug/fiyat': typeof HizmetSlugFiyatRoute
  '/tesisatci/$slug/$service': typeof TesisatciSlugServiceRoute
  '/hizmet/$slug/': typeof HizmetSlugIndexRoute
  '/tesisatci/$slug/': typeof TesisatciSlugIndexRoute
  '/api/public/hooks/automation': typeof ApiPublicHooksAutomationRoute
  '/api/public/hooks/autopilot': typeof ApiPublicHooksAutopilotRoute
  '/api/public/hooks/contact-alert': typeof ApiPublicHooksContactAlertRoute
  '/api/public/hooks/keyword-snapshot': typeof ApiPublicHooksKeywordSnapshotRoute
  '/api/public/hooks/meta-webhook': typeof ApiPublicHooksMetaWebhookRoute
  '/api/public/hooks/publish-social': typeof ApiPublicHooksPublishSocialRoute
  '/api/public/hooks/refresh-analytics': typeof ApiPublicHooksRefreshAnalyticsRoute
  '/api/public/r/$code': typeof ApiPublicRCodeRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/tesisatci/$slug/mahalle/$neighborhood': typeof TesisatciSlugMahalleNeighborhoodRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Desktop-view'
    | '/SEO-overview'
    | '/SEO-overview-bangla'
    | '/acil-tesisatci'
    | '/admin'
    | '/blog-yazma-rehberi'
    | '/cerez-politikasi'
    | '/disavow'
    | '/google-ads'
    | '/google-ads-kurulum'
    | '/hisab'
    | '/hizmetler'
    | '/index-durumu-bangla'
    | '/kvkk'
    | '/og-image.jpg'
    | '/randevu'
    | '/sitemap.xml'
    | '/studio'
    | '/admin/bookings'
    | '/admin/callbacks'
    | '/admin/contact-clicks'
    | '/admin/events'
    | '/admin/keywords'
    | '/admin/login'
    | '/admin/pipeline'
    | '/admin/reviews'
    | '/admin/search-console'
    | '/admin/seo-data'
    | '/admin/seo-writer'
    | '/blog/$slug'
    | '/hisab/activity'
    | '/hisab/capital'
    | '/hisab/customers'
    | '/hisab/files'
    | '/hisab/help'
    | '/hisab/list'
    | '/hisab/login'
    | '/hisab/more'
    | '/hisab/new'
    | '/hisab/parties'
    | '/hisab/products'
    | '/hisab/reports'
    | '/hisab/search'
    | '/hisab/settings'
    | '/hisab/stock'
    | '/hisab/suppliers'
    | '/hisab/warehouse-stock'
    | '/hisab/warehouses'
    | '/hizmet/$slug'
    | '/studio/login'
    | '/tesisatci/$slug'
    | '/admin/'
    | '/blog/'
    | '/hisab/'
    | '/tesisatci/'
    | '/api/hisab/scan'
    | '/hisab/customer/$id'
    | '/hisab/invoice/$id'
    | '/hisab/supplier/$id'
    | '/hizmet/$slug/fiyat'
    | '/tesisatci/$slug/$service'
    | '/hizmet/$slug/'
    | '/tesisatci/$slug/'
    | '/api/public/hooks/automation'
    | '/api/public/hooks/autopilot'
    | '/api/public/hooks/contact-alert'
    | '/api/public/hooks/keyword-snapshot'
    | '/api/public/hooks/meta-webhook'
    | '/api/public/hooks/publish-social'
    | '/api/public/hooks/refresh-analytics'
    | '/api/public/r/$code'
    | '/lovable/email/queue/process'
    | '/tesisatci/$slug/mahalle/$neighborhood'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Desktop-view'
    | '/SEO-overview'
    | '/SEO-overview-bangla'
    | '/acil-tesisatci'
    | '/blog-yazma-rehberi'
    | '/cerez-politikasi'
    | '/disavow'
    | '/google-ads'
    | '/google-ads-kurulum'
    | '/hizmetler'
    | '/index-durumu-bangla'
    | '/kvkk'
    | '/og-image.jpg'
    | '/randevu'
    | '/sitemap.xml'
    | '/studio'
    | '/admin/bookings'
    | '/admin/callbacks'
    | '/admin/contact-clicks'
    | '/admin/events'
    | '/admin/keywords'
    | '/admin/login'
    | '/admin/pipeline'
    | '/admin/reviews'
    | '/admin/search-console'
    | '/admin/seo-data'
    | '/admin/seo-writer'
    | '/blog/$slug'
    | '/hisab/activity'
    | '/hisab/capital'
    | '/hisab/customers'
    | '/hisab/files'
    | '/hisab/help'
    | '/hisab/list'
    | '/hisab/login'
    | '/hisab/more'
    | '/hisab/new'
    | '/hisab/parties'
    | '/hisab/products'
    | '/hisab/reports'
    | '/hisab/search'
    | '/hisab/settings'
    | '/hisab/stock'
    | '/hisab/suppliers'
    | '/hisab/warehouse-stock'
    | '/hisab/warehouses'
    | '/studio/login'
    | '/admin'
    | '/blog'
    | '/hisab'
    | '/tesisatci'
    | '/api/hisab/scan'
    | '/hisab/customer/$id'
    | '/hisab/invoice/$id'
    | '/hisab/supplier/$id'
    | '/hizmet/$slug/fiyat'
    | '/tesisatci/$slug/$service'
    | '/hizmet/$slug'
    | '/tesisatci/$slug'
    | '/api/public/hooks/automation'
    | '/api/public/hooks/autopilot'
    | '/api/public/hooks/contact-alert'
    | '/api/public/hooks/keyword-snapshot'
    | '/api/public/hooks/meta-webhook'
    | '/api/public/hooks/publish-social'
    | '/api/public/hooks/refresh-analytics'
    | '/api/public/r/$code'
    | '/lovable/email/queue/process'
    | '/tesisatci/$slug/mahalle/$neighborhood'
  id:
    | '__root__'
    | '/'
    | '/Desktop-view'
    | '/SEO-overview'
    | '/SEO-overview-bangla'
    | '/acil-tesisatci'
    | '/admin'
    | '/blog-yazma-rehberi'
    | '/cerez-politikasi'
    | '/disavow'
    | '/google-ads'
    | '/google-ads-kurulum'
    | '/hisab'
    | '/hizmetler'
    | '/index-durumu-bangla'
    | '/kvkk'
    | '/og-image.jpg'
    | '/randevu'
    | '/sitemap.xml'
    | '/studio'
    | '/admin/bookings'
    | '/admin/callbacks'
    | '/admin/contact-clicks'
    | '/admin/events'
    | '/admin/keywords'
    | '/admin/login'
    | '/admin/pipeline'
    | '/admin/reviews'
    | '/admin/search-console'
    | '/admin/seo-data'
    | '/admin/seo-writer'
    | '/blog/$slug'
    | '/hisab/activity'
    | '/hisab/capital'
    | '/hisab/customers'
    | '/hisab/files'
    | '/hisab/help'
    | '/hisab/list'
    | '/hisab/login'
    | '/hisab/more'
    | '/hisab/new'
    | '/hisab/parties'
    | '/hisab/products'
    | '/hisab/reports'
    | '/hisab/search'
    | '/hisab/settings'
    | '/hisab/stock'
    | '/hisab/suppliers'
    | '/hisab/warehouse-stock'
    | '/hisab/warehouses'
    | '/hizmet/$slug'
    | '/studio/login'
    | '/tesisatci/$slug'
    | '/admin/'
    | '/blog/'
    | '/hisab/'
    | '/tesisatci/'
    | '/api/hisab/scan'
    | '/hisab/customer/$id'
    | '/hisab/invoice/$id'
    | '/hisab/supplier/$id'
    | '/hizmet/$slug/fiyat'
    | '/tesisatci/$slug/$service'
    | '/hizmet/$slug/'
    | '/tesisatci/$slug/'
    | '/api/public/hooks/automation'
    | '/api/public/hooks/autopilot'
    | '/api/public/hooks/contact-alert'
    | '/api/public/hooks/keyword-snapshot'
    | '/api/public/hooks/meta-webhook'
    | '/api/public/hooks/publish-social'
    | '/api/public/hooks/refresh-analytics'
    | '/api/public/r/$code'
    | '/lovable/email/queue/process'
    | '/tesisatci/$slug/mahalle/$neighborhood'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DesktopViewRoute: typeof DesktopViewRoute
  SEOOverviewRoute: typeof SEOOverviewRoute
  SEOOverviewBanglaRoute: typeof SEOOverviewBanglaRoute
  AcilTesisatciRoute: typeof AcilTesisatciRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlogYazmaRehberiRoute: typeof BlogYazmaRehberiRoute
  CerezPolitikasiRoute: typeof CerezPolitikasiRoute
  DisavowRoute: typeof DisavowRoute
  GoogleAdsRoute: typeof GoogleAdsRoute
  GoogleAdsKurulumRoute: typeof GoogleAdsKurulumRoute
  HisabRoute: typeof HisabRouteWithChildren
  HizmetlerRoute: typeof HizmetlerRoute
  IndexDurumuBanglaRoute: typeof IndexDurumuBanglaRoute
  KvkkRoute: typeof KvkkRoute
  OgImageDotjpgRoute: typeof OgImageDotjpgRoute
  RandevuRoute: typeof RandevuRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StudioRoute: typeof StudioRouteWithChildren
  BlogSlugRoute: typeof BlogSlugRoute
  HizmetSlugRoute: typeof HizmetSlugRouteWithChildren
  TesisatciSlugRoute: typeof TesisatciSlugRouteWithChildren
  BlogIndexRoute: typeof BlogIndexRoute
  TesisatciIndexRoute: typeof TesisatciIndexRoute
  ApiHisabScanRoute: typeof ApiHisabScanRoute
  ApiPublicHooksAutomationRoute: typeof ApiPublicHooksAutomationRoute
  ApiPublicHooksAutopilotRoute: typeof ApiPublicHooksAutopilotRoute
  ApiPublicHooksContactAlertRoute: typeof ApiPublicHooksContactAlertRoute
  ApiPublicHooksKeywordSnapshotRoute: typeof ApiPublicHooksKeywordSnapshotRoute
  ApiPublicHooksMetaWebhookRoute: typeof ApiPublicHooksMetaWebhookRoute
  ApiPublicHooksPublishSocialRoute: typeof ApiPublicHooksPublishSocialRoute
  ApiPublicHooksRefreshAnalyticsRoute: typeof ApiPublicHooksRefreshAnalyticsRoute
  ApiPublicRCodeRoute: typeof ApiPublicRCodeRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/randevu': {
      id: '/randevu'
      path: '/randevu'
      fullPath: '/randevu'
      preLoaderRoute: typeof RandevuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og-image.jpg': {
      id: '/og-image.jpg'
      path: '/og-image.jpg'
      fullPath: '/og-image.jpg'
      preLoaderRoute: typeof OgImageDotjpgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kvkk': {
      id: '/kvkk'
      path: '/kvkk'
      fullPath: '/kvkk'
      preLoaderRoute: typeof KvkkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/index-durumu-bangla': {
      id: '/index-durumu-bangla'
      path: '/index-durumu-bangla'
      fullPath: '/index-durumu-bangla'
      preLoaderRoute: typeof IndexDurumuBanglaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hizmetler': {
      id: '/hizmetler'
      path: '/hizmetler'
      fullPath: '/hizmetler'
      preLoaderRoute: typeof HizmetlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hisab': {
      id: '/hisab'
      path: '/hisab'
      fullPath: '/hisab'
      preLoaderRoute: typeof HisabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/google-ads-kurulum': {
      id: '/google-ads-kurulum'
      path: '/google-ads-kurulum'
      fullPath: '/google-ads-kurulum'
      preLoaderRoute: typeof GoogleAdsKurulumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/google-ads': {
      id: '/google-ads'
      path: '/google-ads'
      fullPath: '/google-ads'
      preLoaderRoute: typeof GoogleAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disavow': {
      id: '/disavow'
      path: '/disavow'
      fullPath: '/disavow'
      preLoaderRoute: typeof DisavowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cerez-politikasi': {
      id: '/cerez-politikasi'
      path: '/cerez-politikasi'
      fullPath: '/cerez-politikasi'
      preLoaderRoute: typeof CerezPolitikasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog-yazma-rehberi': {
      id: '/blog-yazma-rehberi'
      path: '/blog-yazma-rehberi'
      fullPath: '/blog-yazma-rehberi'
      preLoaderRoute: typeof BlogYazmaRehberiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acil-tesisatci': {
      id: '/acil-tesisatci'
      path: '/acil-tesisatci'
      fullPath: '/acil-tesisatci'
      preLoaderRoute: typeof AcilTesisatciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/SEO-overview-bangla': {
      id: '/SEO-overview-bangla'
      path: '/SEO-overview-bangla'
      fullPath: '/SEO-overview-bangla'
      preLoaderRoute: typeof SEOOverviewBanglaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/SEO-overview': {
      id: '/SEO-overview'
      path: '/SEO-overview'
      fullPath: '/SEO-overview'
      preLoaderRoute: typeof SEOOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Desktop-view': {
      id: '/Desktop-view'
      path: '/Desktop-view'
      fullPath: '/Desktop-view'
      preLoaderRoute: typeof DesktopViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tesisatci/': {
      id: '/tesisatci/'
      path: '/tesisatci'
      fullPath: '/tesisatci/'
      preLoaderRoute: typeof TesisatciIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hisab/': {
      id: '/hisab/'
      path: '/'
      fullPath: '/hisab/'
      preLoaderRoute: typeof HisabIndexRouteImport
      parentRoute: typeof HisabRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tesisatci/$slug': {
      id: '/tesisatci/$slug'
      path: '/tesisatci/$slug'
      fullPath: '/tesisatci/$slug'
      preLoaderRoute: typeof TesisatciSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/login': {
      id: '/studio/login'
      path: '/login'
      fullPath: '/studio/login'
      preLoaderRoute: typeof StudioLoginRouteImport
      parentRoute: typeof StudioRoute
    }
    '/hizmet/$slug': {
      id: '/hizmet/$slug'
      path: '/hizmet/$slug'
      fullPath: '/hizmet/$slug'
      preLoaderRoute: typeof HizmetSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hisab/warehouses': {
      id: '/hisab/warehouses'
      path: '/warehouses'
      fullPath: '/hisab/warehouses'
      preLoaderRoute: typeof HisabWarehousesRouteImport
      parentRoute: typeof HisabRoute
    }
    '/hisab/warehouse-stock': {
      id: '/hisab/warehouse-stock'
      path: '/warehouse-stock'
      fullPath: '/hisab/warehouse-stock'
      preLoaderRoute: typeof HisabWarehouseStockRouteImport
      parentRoute: typeof HisabRoute
    }
    '/hisab/suppliers': {
      id: '/hisab/suppliers'
      path: '/suppliers'
      fullPath: '/hisab/suppliers'
      preLoaderRoute: typeof HisabSuppliersRouteImport
      parentRoute: typeof HisabRoute
    }
    '/hisab/stock': {
      id: '/hisab/stock'
      path: '/stock'
      fullPath: '/hisab/stock'
      preLoaderRoute: typeof HisabStockRouteImport
      parentRoute: typeof HisabRoute
    }
    '/hisab/settings': {
      id: '/hisab/settings'
      path: '/settings'
      fullPath: '/hisab/settings'
      preLoaderRoute: typeof HisabSettingsRouteImport
      parentRoute: typeof HisabRoute
    }
    '/hisab/search': {
      id: '/hisab/search'
      path: '/search'
      fullPath: '/hisab/search'
      preLoaderRoute: typeof HisabSearchRouteImport
      parentRoute: typeof HisabRoute
    }
    '/hisab/reports': {
      id: '/hisab/reports'
      path: '/reports'
      fullPath: '/hisab/reports'
      preLoaderRoute: typeof HisabReportsRouteImport
      parentRoute: typeof HisabRoute
    }
    '/hisab/products': {
      id: '/hisab/products'
      path: '/products'
      fullPath: '/hisab/products'
      preLoaderRoute: typeof HisabProductsRouteImport
      parentRoute: typeof HisabRoute
    }
    '/hisab/parties': {
      id: '/hisab/parties'
      path: '/parties'
      fullPath: '/hisab/parties'
      preLoaderRoute: typeof HisabPartiesRouteImport
      parentRoute: typeof HisabRoute
    }
    '/hisab/new': {
      id: '/hisab/new'
      path: '/new'
      fullPath: '/hisab/new'
      preLoaderRoute: typeof HisabNewRouteImport
      parentRoute: typeof HisabRoute
    }
    '/hisab/more': {
      id: '/hisab/more'
      path: '/more'
      fullPath: '/hisab/more'
      preLoaderRoute: typeof HisabMoreRouteImport
      parentRoute: typeof HisabRoute
    }
    '/hisab/login': {
      id: '/hisab/login'
      path: '/login'
      fullPath: '/hisab/login'
      preLoaderRoute: typeof HisabLoginRouteImport
      parentRoute: typeof HisabRoute
    }
    '/hisab/list': {
      id: '/hisab/list'
      path: '/list'
      fullPath: '/hisab/list'
      preLoaderRoute: typeof HisabListRouteImport
      parentRoute: typeof HisabRoute
    }
    '/hisab/help': {
      id: '/hisab/help'
      path: '/help'
      fullPath: '/hisab/help'
      preLoaderRoute: typeof HisabHelpRouteImport
      parentRoute: typeof HisabRoute
    }
    '/hisab/files': {
      id: '/hisab/files'
      path: '/files'
      fullPath: '/hisab/files'
      preLoaderRoute: typeof HisabFilesRouteImport
      parentRoute: typeof HisabRoute
    }
    '/hisab/customers': {
      id: '/hisab/customers'
      path: '/customers'
      fullPath: '/hisab/customers'
      preLoaderRoute: typeof HisabCustomersRouteImport
      parentRoute: typeof HisabRoute
    }
    '/hisab/capital': {
      id: '/hisab/capital'
      path: '/capital'
      fullPath: '/hisab/capital'
      preLoaderRoute: typeof HisabCapitalRouteImport
      parentRoute: typeof HisabRoute
    }
    '/hisab/activity': {
      id: '/hisab/activity'
      path: '/activity'
      fullPath: '/hisab/activity'
      preLoaderRoute: typeof HisabActivityRouteImport
      parentRoute: typeof HisabRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/seo-writer': {
      id: '/admin/seo-writer'
      path: '/seo-writer'
      fullPath: '/admin/seo-writer'
      preLoaderRoute: typeof AdminSeoWriterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/seo-data': {
      id: '/admin/seo-data'
      path: '/seo-data'
      fullPath: '/admin/seo-data'
      preLoaderRoute: typeof AdminSeoDataRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/search-console': {
      id: '/admin/search-console'
      path: '/search-console'
      fullPath: '/admin/search-console'
      preLoaderRoute: typeof AdminSearchConsoleRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pipeline': {
      id: '/admin/pipeline'
      path: '/pipeline'
      fullPath: '/admin/pipeline'
      preLoaderRoute: typeof AdminPipelineRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/keywords': {
      id: '/admin/keywords'
      path: '/keywords'
      fullPath: '/admin/keywords'
      preLoaderRoute: typeof AdminKeywordsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contact-clicks': {
      id: '/admin/contact-clicks'
      path: '/contact-clicks'
      fullPath: '/admin/contact-clicks'
      preLoaderRoute: typeof AdminContactClicksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/callbacks': {
      id: '/admin/callbacks'
      path: '/callbacks'
      fullPath: '/admin/callbacks'
      preLoaderRoute: typeof AdminCallbacksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tesisatci/$slug/': {
      id: '/tesisatci/$slug/'
      path: '/'
      fullPath: '/tesisatci/$slug/'
      preLoaderRoute: typeof TesisatciSlugIndexRouteImport
      parentRoute: typeof TesisatciSlugRoute
    }
    '/hizmet/$slug/': {
      id: '/hizmet/$slug/'
      path: '/'
      fullPath: '/hizmet/$slug/'
      preLoaderRoute: typeof HizmetSlugIndexRouteImport
      parentRoute: typeof HizmetSlugRoute
    }
    '/tesisatci/$slug/$service': {
      id: '/tesisatci/$slug/$service'
      path: '/$service'
      fullPath: '/tesisatci/$slug/$service'
      preLoaderRoute: typeof TesisatciSlugServiceRouteImport
      parentRoute: typeof TesisatciSlugRoute
    }
    '/hizmet/$slug/fiyat': {
      id: '/hizmet/$slug/fiyat'
      path: '/fiyat'
      fullPath: '/hizmet/$slug/fiyat'
      preLoaderRoute: typeof HizmetSlugFiyatRouteImport
      parentRoute: typeof HizmetSlugRoute
    }
    '/hisab/supplier/$id': {
      id: '/hisab/supplier/$id'
      path: '/supplier/$id'
      fullPath: '/hisab/supplier/$id'
      preLoaderRoute: typeof HisabSupplierIdRouteImport
      parentRoute: typeof HisabRoute
    }
    '/hisab/invoice/$id': {
      id: '/hisab/invoice/$id'
      path: '/invoice/$id'
      fullPath: '/hisab/invoice/$id'
      preLoaderRoute: typeof HisabInvoiceIdRouteImport
      parentRoute: typeof HisabRoute
    }
    '/hisab/customer/$id': {
      id: '/hisab/customer/$id'
      path: '/customer/$id'
      fullPath: '/hisab/customer/$id'
      preLoaderRoute: typeof HisabCustomerIdRouteImport
      parentRoute: typeof HisabRoute
    }
    '/api/hisab/scan': {
      id: '/api/hisab/scan'
      path: '/api/hisab/scan'
      fullPath: '/api/hisab/scan'
      preLoaderRoute: typeof ApiHisabScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tesisatci/$slug/mahalle/$neighborhood': {
      id: '/tesisatci/$slug/mahalle/$neighborhood'
      path: '/mahalle/$neighborhood'
      fullPath: '/tesisatci/$slug/mahalle/$neighborhood'
      preLoaderRoute: typeof TesisatciSlugMahalleNeighborhoodRouteImport
      parentRoute: typeof TesisatciSlugRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/r/$code': {
      id: '/api/public/r/$code'
      path: '/api/public/r/$code'
      fullPath: '/api/public/r/$code'
      preLoaderRoute: typeof ApiPublicRCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/refresh-analytics': {
      id: '/api/public/hooks/refresh-analytics'
      path: '/api/public/hooks/refresh-analytics'
      fullPath: '/api/public/hooks/refresh-analytics'
      preLoaderRoute: typeof ApiPublicHooksRefreshAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/publish-social': {
      id: '/api/public/hooks/publish-social'
      path: '/api/public/hooks/publish-social'
      fullPath: '/api/public/hooks/publish-social'
      preLoaderRoute: typeof ApiPublicHooksPublishSocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/meta-webhook': {
      id: '/api/public/hooks/meta-webhook'
      path: '/api/public/hooks/meta-webhook'
      fullPath: '/api/public/hooks/meta-webhook'
      preLoaderRoute: typeof ApiPublicHooksMetaWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/keyword-snapshot': {
      id: '/api/public/hooks/keyword-snapshot'
      path: '/api/public/hooks/keyword-snapshot'
      fullPath: '/api/public/hooks/keyword-snapshot'
      preLoaderRoute: typeof ApiPublicHooksKeywordSnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/contact-alert': {
      id: '/api/public/hooks/contact-alert'
      path: '/api/public/hooks/contact-alert'
      fullPath: '/api/public/hooks/contact-alert'
      preLoaderRoute: typeof ApiPublicHooksContactAlertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/autopilot': {
      id: '/api/public/hooks/autopilot'
      path: '/api/public/hooks/autopilot'
      fullPath: '/api/public/hooks/autopilot'
      preLoaderRoute: typeof ApiPublicHooksAutopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/automation': {
      id: '/api/public/hooks/automation'
      path: '/api/public/hooks/automation'
      fullPath: '/api/public/hooks/automation'
      preLoaderRoute: typeof ApiPublicHooksAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminCallbacksRoute: typeof AdminCallbacksRoute
  AdminContactClicksRoute: typeof AdminContactClicksRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminKeywordsRoute: typeof AdminKeywordsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPipelineRoute: typeof AdminPipelineRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSearchConsoleRoute: typeof AdminSearchConsoleRoute
  AdminSeoDataRoute: typeof AdminSeoDataRoute
  AdminSeoWriterRoute: typeof AdminSeoWriterRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBookingsRoute: AdminBookingsRoute,
  AdminCallbacksRoute: AdminCallbacksRoute,
  AdminContactClicksRoute: AdminContactClicksRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminKeywordsRoute: AdminKeywordsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPipelineRoute: AdminPipelineRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSearchConsoleRoute: AdminSearchConsoleRoute,
  AdminSeoDataRoute: AdminSeoDataRoute,
  AdminSeoWriterRoute: AdminSeoWriterRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface HisabRouteChildren {
  HisabActivityRoute: typeof HisabActivityRoute
  HisabCapitalRoute: typeof HisabCapitalRoute
  HisabCustomersRoute: typeof HisabCustomersRoute
  HisabFilesRoute: typeof HisabFilesRoute
  HisabHelpRoute: typeof HisabHelpRoute
  HisabListRoute: typeof HisabListRoute
  HisabLoginRoute: typeof HisabLoginRoute
  HisabMoreRoute: typeof HisabMoreRoute
  HisabNewRoute: typeof HisabNewRoute
  HisabPartiesRoute: typeof HisabPartiesRoute
  HisabProductsRoute: typeof HisabProductsRoute
  HisabReportsRoute: typeof HisabReportsRoute
  HisabSearchRoute: typeof HisabSearchRoute
  HisabSettingsRoute: typeof HisabSettingsRoute
  HisabStockRoute: typeof HisabStockRoute
  HisabSuppliersRoute: typeof HisabSuppliersRoute
  HisabWarehouseStockRoute: typeof HisabWarehouseStockRoute
  HisabWarehousesRoute: typeof HisabWarehousesRoute
  HisabIndexRoute: typeof HisabIndexRoute
  HisabCustomerIdRoute: typeof HisabCustomerIdRoute
  HisabInvoiceIdRoute: typeof HisabInvoiceIdRoute
  HisabSupplierIdRoute: typeof HisabSupplierIdRoute
}

const HisabRouteChildren: HisabRouteChildren = {
  HisabActivityRoute: HisabActivityRoute,
  HisabCapitalRoute: HisabCapitalRoute,
  HisabCustomersRoute: HisabCustomersRoute,
  HisabFilesRoute: HisabFilesRoute,
  HisabHelpRoute: HisabHelpRoute,
  HisabListRoute: HisabListRoute,
  HisabLoginRoute: HisabLoginRoute,
  HisabMoreRoute: HisabMoreRoute,
  HisabNewRoute: HisabNewRoute,
  HisabPartiesRoute: HisabPartiesRoute,
  HisabProductsRoute: HisabProductsRoute,
  HisabReportsRoute: HisabReportsRoute,
  HisabSearchRoute: HisabSearchRoute,
  HisabSettingsRoute: HisabSettingsRoute,
  HisabStockRoute: HisabStockRoute,
  HisabSuppliersRoute: HisabSuppliersRoute,
  HisabWarehouseStockRoute: HisabWarehouseStockRoute,
  HisabWarehousesRoute: HisabWarehousesRoute,
  HisabIndexRoute: HisabIndexRoute,
  HisabCustomerIdRoute: HisabCustomerIdRoute,
  HisabInvoiceIdRoute: HisabInvoiceIdRoute,
  HisabSupplierIdRoute: HisabSupplierIdRoute,
}

const HisabRouteWithChildren = HisabRoute._addFileChildren(HisabRouteChildren)

interface StudioRouteChildren {
  StudioLoginRoute: typeof StudioLoginRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioLoginRoute: StudioLoginRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

interface HizmetSlugRouteChildren {
  HizmetSlugFiyatRoute: typeof HizmetSlugFiyatRoute
  HizmetSlugIndexRoute: typeof HizmetSlugIndexRoute
}

const HizmetSlugRouteChildren: HizmetSlugRouteChildren = {
  HizmetSlugFiyatRoute: HizmetSlugFiyatRoute,
  HizmetSlugIndexRoute: HizmetSlugIndexRoute,
}

const HizmetSlugRouteWithChildren = HizmetSlugRoute._addFileChildren(
  HizmetSlugRouteChildren,
)

interface TesisatciSlugRouteChildren {
  TesisatciSlugServiceRoute: typeof TesisatciSlugServiceRoute
  TesisatciSlugIndexRoute: typeof TesisatciSlugIndexRoute
  TesisatciSlugMahalleNeighborhoodRoute: typeof TesisatciSlugMahalleNeighborhoodRoute
}

const TesisatciSlugRouteChildren: TesisatciSlugRouteChildren = {
  TesisatciSlugServiceRoute: TesisatciSlugServiceRoute,
  TesisatciSlugIndexRoute: TesisatciSlugIndexRoute,
  TesisatciSlugMahalleNeighborhoodRoute: TesisatciSlugMahalleNeighborhoodRoute,
}

const TesisatciSlugRouteWithChildren = TesisatciSlugRoute._addFileChildren(
  TesisatciSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DesktopViewRoute: DesktopViewRoute,
  SEOOverviewRoute: SEOOverviewRoute,
  SEOOverviewBanglaRoute: SEOOverviewBanglaRoute,
  AcilTesisatciRoute: AcilTesisatciRoute,
  AdminRoute: AdminRouteWithChildren,
  BlogYazmaRehberiRoute: BlogYazmaRehberiRoute,
  CerezPolitikasiRoute: CerezPolitikasiRoute,
  DisavowRoute: DisavowRoute,
  GoogleAdsRoute: GoogleAdsRoute,
  GoogleAdsKurulumRoute: GoogleAdsKurulumRoute,
  HisabRoute: HisabRouteWithChildren,
  HizmetlerRoute: HizmetlerRoute,
  IndexDurumuBanglaRoute: IndexDurumuBanglaRoute,
  KvkkRoute: KvkkRoute,
  OgImageDotjpgRoute: OgImageDotjpgRoute,
  RandevuRoute: RandevuRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StudioRoute: StudioRouteWithChildren,
  BlogSlugRoute: BlogSlugRoute,
  HizmetSlugRoute: HizmetSlugRouteWithChildren,
  TesisatciSlugRoute: TesisatciSlugRouteWithChildren,
  BlogIndexRoute: BlogIndexRoute,
  TesisatciIndexRoute: TesisatciIndexRoute,
  ApiHisabScanRoute: ApiHisabScanRoute,
  ApiPublicHooksAutomationRoute: ApiPublicHooksAutomationRoute,
  ApiPublicHooksAutopilotRoute: ApiPublicHooksAutopilotRoute,
  ApiPublicHooksContactAlertRoute: ApiPublicHooksContactAlertRoute,
  ApiPublicHooksKeywordSnapshotRoute: ApiPublicHooksKeywordSnapshotRoute,
  ApiPublicHooksMetaWebhookRoute: ApiPublicHooksMetaWebhookRoute,
  ApiPublicHooksPublishSocialRoute: ApiPublicHooksPublishSocialRoute,
  ApiPublicHooksRefreshAnalyticsRoute: ApiPublicHooksRefreshAnalyticsRoute,
  ApiPublicRCodeRoute: ApiPublicRCodeRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
